version: '3.8'

services:
  product-query-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TOP_K_RETRIEVAL=3
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - LLM_MODEL=claude-3-haiku-20240307
      - VECTOR_STORE_PATH=/app/vector_store
      - LOG_LEVEL=INFO
    volumes:
      - ./vector_store:/app/vector_store
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped